apiVersion: v1
kind: Service
metadata:
  name: test1-service # Up to you
spec:
  selector:
    app: test1-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1 # Deployment name
spec:
  replicas: 3 # Scaling
  selector:
    matchLabels:
      app: test1-app # (key - value 값으로 자유롭게 지정)
  template:
    metadata:
      labels:
        app: test1-app 
    spec: # information about pods
      containers:
        - name: test1-node # naming container (Up to you)
          image: minercode/test2:2
        # for multiple containers...
        # - name: ...
        #   image: ...
