apiVersion: v1
kind: Service
metadata:
  name: test1-service # Up to you
spec:
  selector:
    app: test1-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
